services:
  generator:
    build: .
    container_name: mc-map-to-jpg
    volumes:
      - ./data:/app/data:ro
      - ./output:/app/output
      # Edit the path to your Minecraft world save directory
      - "/.../minecraft/saves/world:/app/world"
    environment:
      - MAP_PATH=/app/world
      - PROGRESS_TEXT=0
      # Edit the coordinates here or set them as environment variables (or in .env) when running the container
      - X1=${X1:--50}
      - Z1=${Z1:--50}
      - X2=${X2:-50}
      - Z2=${Z2:-50}